
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 1000
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/visited?serverTimezone=UTC"
    username: sa


